### PR TITLE
* Quick and dirty patch to make the backdoor load on Windows 11.

### PR DESCRIPTION
**Pull request by crackinglandia**
I needed to make the backdoor work on Windows 11 but it was having some troubles finding the vm_exit handler. The fix is easy but not all backdoor features are available though. Some of them are failing, for example, those regarding driver loading in SK. Anyway, I'm sharing this in case anyone else ran into this problem.

### CODE REVIEW

**Comment by Cr4sh** [comment]
Thank you for this fix! Will review, test & merge it as soon as possible. 

Regarding other backdoor features -- I think it should be ain't difficult to fix them in order to achieve full Win 11 support, but unfortunately I don't have much time for this project right now to look into. Anyway, will try to figure out something once I'll have some free time.

**Comment by crackinglandia** [comment]
If I remember correctly, some of the features I looked at were also related to some pattern search. I'll try to dig further to see if I can fix them all.

**Comment by Cr4sh** [comment]
There's at least two places with code signatures in secure kernel related code, I think the most obvious problems should be smowhere there:

https://github.com/Cr4sh/s6_pcie_microblaze/blob/4d50dd99b3ac252fc99f81ebd133345ca359e857/python/payloads/DmaBackdoorHv/backdoor_client/backdoor_client/backdoor_client.cpp#L1696

https://github.com/Cr4sh/s6_pcie_microblaze/blob/4d50dd99b3ac252fc99f81ebd133345ca359e857/python/payloads/DmaBackdoorHv/backdoor_client/backdoor_client/backdoor_client.cpp#L1796

Another place in the code that might be broken on different Windows version is `PROCESSOR_START_BLOCK` related stuff since this structure could be changed:
https://github.com/Cr4sh/s6_pcie_microblaze/blob/4d50dd99b3ac252fc99f81ebd133345ca359e857/python/payloads/DmaBackdoorHv/backdoor_client/backdoor_client/backdoor_client.cpp#L238

It's also worth to check IUM trustlets loader that uses udis86 disassembly engine to analyze huge amounts of `skci.dll` executable code in order to find & patch integrity checks, there could be some issues as well:

https://github.com/Cr4sh/s6_pcie_microblaze/blob/4d50dd99b3ac252fc99f81ebd133345ca359e857/python/payloads/DmaBackdoorHv/backdoor_client/trustlet_loader/trustlet_loader.cpp#L129

Thank you for your efforts!

**Comment by crackinglandia** [comment]
Great, thanks for the notes, I'll start with that then!

> There's at least two places with code signatures in secure kernel related code, I think the most obvious problems should be smowhere there:
> 
> https://github.com/Cr4sh/s6_pcie_microblaze/blob/4d50dd99b3ac252fc99f81ebd133345ca359e857/python/payloads/DmaBackdoorHv/backdoor_client/backdoor_client/backdoor_client.cpp#L1696
> 
> https://github.com/Cr4sh/s6_pcie_microblaze/blob/4d50dd99b3ac252fc99f81ebd133345ca359e857/python/payloads/DmaBackdoorHv/backdoor_client/backdoor_client/backdoor_client.cpp#L1796
> 
> Another place in the code that might be broken on different Windows version is `PROCESSOR_START_BLOCK` related stuff since this structure could be changed:
> 
> https://github.com/Cr4sh/s6_pcie_microblaze/blob/4d50dd99b3ac252fc99f81ebd133345ca359e857/python/payloads/DmaBackdoorHv/backdoor_client/backdoor_client/backdoor_client.cpp#L238
> 
> It's also worth to check IUM trustlets loader that uses udis86 disassembly engine to analyze huge amounts of `skci.dll` executable code in order to find & patch integrity checks, there could be some issues as well:
> 
> https://github.com/Cr4sh/s6_pcie_microblaze/blob/4d50dd99b3ac252fc99f81ebd133345ca359e857/python/payloads/DmaBackdoorHv/backdoor_client/trustlet_loader/trustlet_loader.cpp#L129
> 
> Thank you for your efforts!

**Comment by gabriel-maxx** [comment]
@crackinglandia hello could you try to add support for DmaBackdoorBoot?

**Comment by crackinglandia** [comment]
> @crackinglandia hello could you try to add support for DmaBackdoorBoot?

Hey!. Sure. I've been busy lately but I'll do it after fixing and reviewing what Cr4sh suggested.

**Comment by Cr4sh** [comment]
In recent commits I implemented basic Windows 11 support, both 21H2 and 22H2, for backdoor and client. At this moment all client program commands works fine on Windows 11 except `--sk-inject` and `--sk-debug-enable` which requires more changes in order to get it function.

**Comment by gabriel-maxx** [comment]
> In recent commits I implemented basic Windows 11 support, both 21H2 and 22H2, for backdoor and client. At this moment all client program commands works fine on Windows 11 except `--sk-inject` and `--sk-debug-enable` which requires more changes in order to get it function.

Hello, what about DmaBackdoorBoot?

**Pull request closed without merging**
